---

- name: Ghost Deployment
  shell: kubectl apply -f roles/deploy-ghost/templates/ghost-deployment.yml

- name: Service Ghost
  shell: kubectl apply -f roles/deploy-ghost/templates/ghost-service.yml


