---
# Playbook to deploy Ghost and its components
- name: Deploy MySQL DB
  hosts: localhost
  gather_facts: false
  roles:
    - mysql

- name: Deploy Ghost APP
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  roles:
    - deploy-ghost

- name: Deploy Dashboard
  hosts: localhost
  roles:
    - undeploy_monit
    - deploy_monit

