---
# Playbook to deploy Ghost and its components
- name: Deploy MySQL DB
  hosts: localhost
  gather_facts: false
  roles:
    - mysql

- name: Wait
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for 10 seconds
      wait_for:
        timeout: 10

- name: Deploy Ghost APP
  hosts: localhost
  gather_facts: false
  roles:
    - deploy-ghost
