---
- name: Create Ghost Autoscaler
  hosts: localhost
  tasks:
  - name: Create Autoscaler
      api_version: autoscaling/v2beta1
      kind: HorizontalPodAutoscaler
      name: ghost-autoscaler
      scaleTargetRef:
        api_version: apps/v1
        kind: Deployment
        name: ghost-deployment
      min_replicas: 1
      max_replicas: 10
      metrics:
      - type: Resource
        resource:
          name: cpu
          target_average_utilization: 20 # 20% of the CPU para teste, mudar futuramente
      state: present