---
# Playbook to undeploy Ghost and its component

- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
    - undeploy-ghost
    - {role: undeploy-ghost-pv, when: delete_data is defined and delete_data == 'true'}
    - undeploy_monit