- name: Check Dashboards
  shell: gcloud monitoring dashboards list --filter="displayName='monitoring'"
  register: result
  retries: 10
  delay: 10

- name: Change File
  template:
    src:  templates/monitoring.yml
    dest: roles/monit/monitoring.json

- name: Create Dashboard
  shell: "gcloud monitoring dashboards create --config-from-file=roles/monit/monitoring.json"
  when: result.stdout == ""

- name: Create Agents 
  shell: ":> agents_to_install.csv && \
          echo '\"projects/ascn-ghost-369310/zones/us-central1-a/instances/gke-ascn-cluster-default-pool-37073308-4s7z\",\"[{\"\"type\"\":\"\"ops-agent\"\"}]\"' >> agents_to_install.csv && \
          echo '\"projects/ascn-ghost-369310/zones/us-central1-a/instances/gke-ascn-cluster-default-pool-37073308-kpj1\",\"[{\"\"type\"\":\"\"ops-agent\"\"}]\"' >> agents_to_install.csv && \
          curl -sSO https://dl.google.com/cloudagents/mass-provision-google-cloud-ops-agents.py && \
          python3 mass-provision-google-cloud-ops-agents.py --file agents_to_install.csv"

