---
- name: Undeploy MySQL service
  shell: kubectl delete service mysql-service


- name: Undeploy MySQL Deployment
  shell: kubectl delete deployment mysql-deployment


- name: Undeploy Ghost Service
  shell: kubectl delete service ghost-service


- name: Undeploy Ghost Deployment
  shell: kubectl delete deployment ghost-deployment

    