---

- name: MySQL PVC
  shell: kubectl apply -f roles/mysql/kubernetes/mysql-pvc.yml

- name: MySQL Deployment
  shell: |
    export PASSWORD={{ admin_password }}
    envsubst < roles/mysql/kubernetes/mysql-deployment.yml | kubectl apply -f -
    unset PASSWORD

- name: Service MySQL
  shell: kubectl apply -f roles/mysql/kubernetes/mysql-service.yml

- name: Get MySQL PersistentVolume
  shell: kubectl get pv | grep pvc | awk '{print $1}'
  register: mysql_pv
  until: mysql_pv.stdout != ""

- name: Change to Retain Policy
  shell: kubectl patch pv {{ mysql_pv.stdout }} -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
