---

- name: Create MySQL Persistent Volume Claim
  command: kubectl apply -f roles/mysql/tasks/mysql-pvc.yml

- name: Create MySQL Service
  command: kubectl apply -f roles/mysql/tasks/mysql-service.yml

- name: Create MySQL Deployment
  command: kubectl apply -f roles/mysql/tasks/mysql-deployment.yml

