---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80