---
# Service for exposing Ghost
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - targetPort: 2368 # port that containers are listening on
      port: 80 # port exposed internally in the cluster
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
