---
# Deployment for deploying Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: #Mudar isto de acordo as specs do ghost  
        - name: url
          value: http://35.192.38.212:80/
        #DB
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__database
          value: ghost
        - name: database__connection__user
          value: admin
        - name: database__connection__password
          value: "$PASSWORD"
        - name: mail__transport
          value: "SMTP"
        - name: mail__from
          value: "ASCN 19 <ascn@example.com>"
        - name: mail__options__host
          value: "smtp.mailtrap.io"
        - name: mail__options__port
          value: "2525"
        - name: mail__options__auth__user
          value: "b3edca30dbbb47"
        - name: mail__options__auth__pass
          value: "$PASSWORD_MAIL"
        - name: mail__options__service
          value: "Mailtrap"
        ports:
        - containerPort: 2368
        resources:
          requests: 
            cpu: "100m" # Make sure that at least 1 core is available for requests
          limits:
            cpu: "100m" # 1 core upper limit
