---

- name: Update system packages
  become: yes
  apt:
    update_cache: yes
    upgrade: no
  

---
- name: Clone Ghost repository 
  git:
    repo: https://github.com/TryGhost/Ghost.git
    dest: ~/ghost

- name: Install node and npm
  tasks:
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Deploy Ghost
  tasks:
    - name: npm install ghost-cli -g
      community.general.npm:
        name: ghost-cli
        global: true
    - name: ghost install  
      shell: ghost install